# -*- coding: utf-8 -*-

sudo: true

language: python

python:
  - "3.5"

env:
  - TOXENV=py35

before_install:
  - sudo add-apt-repository ppa:git-core/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install git
install:
  - git --version
  - pip install tox

script:
  - GIT_USER="Travis CI" GIT_EMAIL="noreply@travis-ci.org" tox
